package main

import (
	"encoding/json"
	"log"
	"math"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"time"

	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/components"
	"github.com/go-echarts/go-echarts/v2/opts"
	"github.com/go-echarts/go-echarts/v2/types"
	"github.com/joho/godotenv"
	"github.com/moby/buildkit-bench/util/candidates"
	"github.com/moby/buildkit-bench/util/github/gha"
	"github.com/moby/buildkit-bench/util/gotest"
	"github.com/moby/buildkit-bench/util/testutil"
	"github.com/montanaflynn/stats"
	"github.com/pkg/errors"
	"github.com/zeebo/xxh3"
)

type genCmd struct {
	Files []string `kong:"arg='',name='files',required,help='Benchmark results files generated by parse command.'"`

	Name           string `kong:"name='name',help='Name of the report.'"`
	Config         string `kong:"name='config',required,default='testconfig.yml',help='Test config file.'"`
	Output         string `kong:"name='output',default='./bin/gen/benchmarks.html',help='File to write the HTML report to.'"`
	Project        string `kong:"name='project',enum='buildkit,buildx',default='buildkit',help='Project type.'"`
	Candidates     string `kong:"name='candidates',help='Candidates file.'"`
	GHAEvent       string `kong:"name='gha-event',help='GitHub Actions payload JSON file.'"`
	Envs           string `kong:"name='envs',help='Environment variables file.'"`
	ValidationMode string `kong:"name='validation-mode',enum='sloppy,strict',default='sloppy',help='Validation mode.'"`
}

type metricChart struct {
	unit   string
	cfg    testutil.TestConfigMetric
	values map[string][]float64
}

func (c *genCmd) Run(ctx *Context) error {
	benchmarks, err := gotest.MergeBenchmarks(c.Files)
	if err != nil {
		return err
	}
	if ctx.Debug {
		b, _ := json.MarshalIndent(benchmarks, "", "  ")
		log.Printf("%s", string(b))
	}
	if err := c.validateBenchmarks(benchmarks); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(c.Output), 0755); err != nil {
		return errors.Wrap(err, "failed to create output directory")
	}
	return c.writeHTML(benchmarks)
}

func (c *genCmd) validateBenchmarks(benchmarks map[string]gotest.Benchmark) error {
	log.Printf("Validating %d benchmark results based on %s", len(benchmarks), c.Config)
	tc, err := testutil.LoadTestConfig(c.Config)
	if err != nil {
		return err
	}
	seen := make(map[string]struct{})
	for _, benchmark := range benchmarks {
		if _, ok := seen[benchmark.Name]; !ok {
			seen[benchmark.Name] = struct{}{}
		}
		bm, err := tc.BenchmarkConfig(benchmark.Name)
		if err != nil {
			return err
		}
		for _, run := range benchmark.Runs {
			for unit := range run.Extra {
				if _, ok := bm.Metrics[unit]; !ok {
					return errors.Errorf("unknown metric %q for benchmark %q", unit, benchmark.Name)
				}
			}
		}
	}
	if c.ValidationMode == "strict" {
		for rootName, bms := range tc.Runs {
			for testName, testConfig := range bms {
				if testConfig.Scope != "" && testConfig.Scope != c.Project {
					continue
				}
				if _, ok := seen[rootName+"/"+testName]; !ok {
					return errors.Errorf("missing benchmark result for %q", rootName+"/"+testName)
				}
			}
		}
	}
	return nil
}

func (c *genCmd) writeHTML(benchmarks map[string]gotest.Benchmark) error {
	log.Printf("Generating HTML report to %s", c.Output)
	benchmarksRuns := make(map[string][]gotest.BenchmarkRun)
	for _, benchmark := range benchmarks {
		br, ok := benchmarksRuns[benchmark.Name]
		if ok {
			benchmarksRuns[benchmark.Name] = append(br, benchmark.Runs...)
		} else {
			benchmarksRuns[benchmark.Name] = benchmark.Runs
		}
	}

	tc, err := testutil.LoadTestConfig(c.Config)
	if err != nil {
		return err
	}

	var envs map[string]string
	if c.Envs != "" {
		envs, err = godotenv.Read(c.Envs)
		if err != nil {
			return err
		}
	}

	if c.GHAEvent != "" {
		ghaEventName, ok := envs["GITHUB_EVENT_NAME"]
		if !ok {
			return errors.New("missing GITHUB_EVENT_NAME in envs")
		}
		if ghaEventName != "schedule" { // https://github.com/moby/buildkit-bench/issues/141
			_, err = gha.ParseEventFile(ghaEventName, c.GHAEvent)
			if err != nil {
				return err
			}
		}
	}

	var sortedRefs []candidates.Ref
	if c.Candidates != "" {
		cds, err := candidates.Load(c.Candidates)
		if err != nil {
			return errors.Wrapf(err, "failed to load candidates from %s", c.Candidates)
		}
		sortedRefs = cds.Sorted()
	}

	var cps []components.Charter

	benchmarkKeys := make([]string, 0, len(benchmarksRuns))
	for k := range benchmarksRuns {
		benchmarkKeys = append(benchmarkKeys, k)
	}
	sort.Strings(benchmarkKeys)
	for _, name := range benchmarkKeys {
		runs := benchmarksRuns[name]
		bc, err := tc.BenchmarkConfig(name)
		if err != nil {
			return err
		}

		metrics := make(map[string]map[string][]float64)
		for _, run := range runs {
			for unit := range bc.Metrics {
				ref := run.Ref
				if c.Project == "buildx" {
					ref = run.Buildx
				}
				if _, ok := metrics[unit]; !ok {
					metrics[unit] = make(map[string][]float64)
				}
				if v, ok := run.Extra[unit]; ok {
					metrics[unit][ref] = append(metrics[unit][ref], v)
				} else if unit == string(testutil.MetricDuration) {
					metrics[unit][ref] = append(metrics[unit][ref], time.Duration(run.NsPerOp).Seconds())
				} else {
					return errors.Errorf("missing metric %q for run %s", unit, ref)
				}
			}
		}

		chartComponents, err := benchmarkChartComponents(chartGlobalOptions(bc.Description, name), bc, sortedRefs, name, metrics)
		if err != nil {
			return err
		}
		cps = append(cps, chartComponents...)
	}

	page := components.NewPage()
	page.PageTitle = "BuildKit Benchmarks"
	page.Layout = components.PageFlexLayout
	page.AddCharts(cps...)

	f, err := os.Create(c.Output)
	if err != nil {
		return errors.Wrap(err, "failed to create file")
	}
	defer f.Close()

	if err := page.Render(f); err != nil {
		return errors.Wrap(err, "failed to render page")
	}

	return nil
}

func chartGlobalOptions(title, subtitle string) []charts.GlobalOpts {
	return []charts.GlobalOpts{
		charts.WithTitleOpts(opts.Title{
			Title:    title,
			Subtitle: subtitle,
		}),
		charts.WithDataZoomOpts(opts.DataZoom{
			Type: "slider",
		}),
		charts.WithToolboxOpts(opts.Toolbox{
			Show:   opts.Bool(true),
			Orient: "horizontal",
			Right:  "100",
			Feature: &opts.ToolBoxFeature{
				DataZoom: &opts.ToolBoxFeatureDataZoom{
					Show: opts.Bool(true),
				},
				Restore: &opts.ToolBoxFeatureRestore{
					Show: opts.Bool(true),
				},
				SaveAsImage: &opts.ToolBoxFeatureSaveAsImage{
					Show: opts.Bool(true),
				},
			},
		}),
	}
}

func benchmarkChartComponents(globalOpts []charts.GlobalOpts, bc *testutil.TestConfigBenchmark, sortedRefs []candidates.Ref, name string, metrics map[string]map[string][]float64) ([]components.Charter, error) {
	var cps []components.Charter
	combinedMetrics := make(map[string]struct{})
	if chart, ok, err := chartDurationAlloc(globalOpts, bc, sortedRefs, name, metrics); err != nil {
		return nil, err
	} else if ok {
		cps = append(cps, chart)
		combinedMetrics[string(testutil.MetricDuration)] = struct{}{}
		combinedMetrics[string(testutil.MetricAlloc)] = struct{}{}
	}

	for _, unit := range sortedMetricUnits(metrics) {
		if _, ok := combinedMetrics[unit]; ok {
			continue
		}
		cfg := bc.Metrics[unit]
		switch cfg.Chart {
		case types.ChartBar:
			chart, err := chartBar(globalOpts, cfg, sortedRefs, name, unit, metrics[unit])
			if err != nil {
				return nil, err
			}
			cps = append(cps, chart)
		case types.ChartBoxPlot:
			chart, err := chartBoxPlot(globalOpts, cfg, sortedRefs, name, unit, metrics[unit])
			if err != nil {
				return nil, err
			}
			cps = append(cps, chart)
		default:
			return nil, errors.Errorf("unknown chart type %q for metric %q", cfg.Chart, unit)
		}
	}

	return cps, nil
}

func chartDurationAlloc(globalOpts []charts.GlobalOpts, bc *testutil.TestConfigBenchmark, sortedRefs []candidates.Ref, name string, metrics map[string]map[string][]float64) (components.Charter, bool, error) {
	durationUnit := string(testutil.MetricDuration)
	allocUnit := string(testutil.MetricAlloc)

	durationCfg, ok := bc.Metrics[durationUnit]
	if !ok {
		return nil, false, nil
	}
	allocCfg, ok := bc.Metrics[allocUnit]
	if !ok {
		return nil, false, nil
	}
	if durationCfg.Chart != types.ChartBoxPlot || allocCfg.Chart != types.ChartBoxPlot {
		return nil, false, nil
	}

	durationValues, ok := metrics[durationUnit]
	if !ok {
		return nil, false, nil
	}
	allocValues, ok := metrics[allocUnit]
	if !ok {
		return nil, false, nil
	}

	chart, err := chartBoxPlotOverlay(globalOpts, sortedRefs, name,
		metricChart{unit: durationUnit, cfg: durationCfg, values: durationValues},
		metricChart{unit: allocUnit, cfg: allocCfg, values: allocValues},
	)
	if err != nil {
		return nil, false, err
	}
	return chart, true, nil
}

func chartBar(globalOpts []charts.GlobalOpts, cfg testutil.TestConfigMetric, sortedRefs []candidates.Ref, name, unit string, values map[string][]float64) (components.Charter, error) {
	var data []opts.BarData
	refs, valueSets := orderedMetricValues(sortedRefs, values)
	for _, v := range valueSets {
		m, err := stats.Median(v)
		if err != nil {
			return nil, errors.Wrap(err, "failed to calculate median")
		}
		mr, err := stats.Round(m, 5)
		if err != nil {
			return nil, errors.Wrap(err, "failed to round median")
		}
		data = append(data, opts.BarData{Value: mr})
	}

	var seriesOpts []charts.SeriesOpts
	if cfg.Average {
		seriesOpts = append(seriesOpts, charts.WithMarkLineNameTypeItemOpts(
			opts.MarkLineNameTypeItem{Name: "Avg", Type: "average", LineStyle: &opts.LineStyle{
				Color: "#91cc75",
				Width: 2,
			}},
		))
	}

	chart := charts.NewBar()
	chart.ChartID = chartIdentity(name, unit)
	chart.SetGlobalOptions(globalOpts...)
	chart.SetXAxis(refs).AddSeries(cfg.Description, data).SetSeriesOptions(seriesOpts...)
	return chart, nil
}

func chartBoxPlot(globalOpts []charts.GlobalOpts, cfg testutil.TestConfigMetric, sortedRefs []candidates.Ref, name, unit string, values map[string][]float64) (components.Charter, error) {
	refs, valueSets := orderedMetricValues(sortedRefs, values)
	data, err := boxPlotSeriesData(valueSets)
	if err != nil {
		return nil, err
	}

	chart := charts.NewBoxPlot()
	chart.ChartID = chartIdentity(name, unit)
	chart.SetGlobalOptions(globalOpts...)

	chart.SetXAxis(refs).AddSeries(cfg.Description, data)

	return chart, nil
}

func chartBoxPlotOverlay(globalOpts []charts.GlobalOpts, sortedRefs []candidates.Ref, name string, primary, secondary metricChart) (components.Charter, error) {
	refs, primaryValues, secondaryValues := orderedCommonMetricValues(sortedRefs, primary.values, secondary.values)
	primaryData, err := boxPlotSeriesData(primaryValues)
	if err != nil {
		return nil, err
	}
	secondaryData, err := boxPlotSeriesData(secondaryValues)
	if err != nil {
		return nil, err
	}

	chart := charts.NewBoxPlot()
	chart.ChartID = chartIdentity(name, primary.unit+"+"+secondary.unit)
	chart.ExtendYAxis(opts.YAxis{})
	chartOpts := append([]charts.GlobalOpts{}, globalOpts...)
	chartOpts = append(chartOpts,
		charts.WithYAxisOpts(metricYAxis(primary.cfg, "left"), 0),
		charts.WithYAxisOpts(metricYAxis(secondary.cfg, "right"), 1),
	)
	chart.SetGlobalOptions(chartOpts...)
	chart.SetXAxis(refs).AddSeries(primary.cfg.Description, primaryData, withYAxisIndex(0))

	overlay := charts.NewBoxPlot()
	overlay.AddSeries(secondary.cfg.Description, secondaryData, withYAxisIndex(1))
	chart.Overlap(overlay)

	return chart, nil
}

func metricYAxis(cfg testutil.TestConfigMetric, position string) opts.YAxis {
	return opts.YAxis{
		Name:         cfg.Description,
		NameLocation: "middle",
		NameGap:      45,
		Type:         "value",
		Position:     position,
		AlignTicks:   opts.Bool(true),
	}
}

func withYAxisIndex(index int) charts.SeriesOpts {
	return charts.WithSeriesOpts(func(s *charts.SingleSeries) {
		s.YAxisIndex = index
	})
}

func sortedMetricUnits(metrics map[string]map[string][]float64) []string {
	units := make([]string, 0, len(metrics))
	for unit := range metrics {
		units = append(units, unit)
	}
	sort.Strings(units)
	return units
}

func orderedMetricValues(sortedRefs []candidates.Ref, values map[string][]float64) ([]string, [][]float64) {
	var refs []string
	var valueSets [][]float64
	if len(sortedRefs) == 0 {
		refs = make([]string, 0, len(values))
		for ref := range values {
			refs = append(refs, ref)
		}
		sort.Strings(refs)
		for _, ref := range refs {
			valueSets = append(valueSets, values[ref])
		}
		return refs, valueSets
	}

	for _, ref := range sortedRefs {
		v, ok := values[ref.Name]
		if !ok {
			continue
		}
		refs = append(refs, ref.Name)
		valueSets = append(valueSets, v)
	}
	return refs, valueSets
}

func orderedCommonMetricValues(sortedRefs []candidates.Ref, primary, secondary map[string][]float64) ([]string, [][]float64, [][]float64) {
	var refs []string
	var primaryValues [][]float64
	var secondaryValues [][]float64
	if len(sortedRefs) == 0 {
		refs = make([]string, 0, len(primary))
		for ref := range primary {
			if _, ok := secondary[ref]; ok {
				refs = append(refs, ref)
			}
		}
		sort.Strings(refs)
		for _, ref := range refs {
			primaryValues = append(primaryValues, primary[ref])
			secondaryValues = append(secondaryValues, secondary[ref])
		}
		return refs, primaryValues, secondaryValues
	}

	for _, ref := range sortedRefs {
		pv, ok := primary[ref.Name]
		if !ok {
			continue
		}
		sv, ok := secondary[ref.Name]
		if !ok {
			continue
		}
		refs = append(refs, ref.Name)
		primaryValues = append(primaryValues, pv)
		secondaryValues = append(secondaryValues, sv)
	}
	return refs, primaryValues, secondaryValues
}

func boxPlotSeriesData(valueSets [][]float64) ([]opts.BoxPlotData, error) {
	var data []opts.BoxPlotData
	for _, v := range valueSets {
		plotData, err := createBoxPlotData(v)
		if err != nil {
			return nil, errors.Wrap(err, "failed to create box plot data")
		}
		data = append(data, opts.BoxPlotData{Value: plotData})
	}
	return data, nil
}

func chartIdentity(name, unit string) string {
	h := xxh3.New()
	h.WriteString(name)
	h.Write([]byte{0})
	h.WriteString(unit)
	h.Write([]byte{0})
	return strconv.FormatUint(h.Sum64(), 10)
}

func createBoxPlotData(data []float64) ([]float64, error) {
	minv, err := stats.Min(data)
	if err != nil {
		return nil, errors.Wrap(err, "failed to calculate min")
	}
	maxv, err := stats.Max(data)
	if err != nil {
		return nil, errors.Wrap(err, "failed to calculate max")
	}
	q, err := stats.Quartile(data)
	if err != nil {
		return nil, errors.Wrap(err, "failed to calculate quartiles")
	}
	values := []float64{
		minv,
		q.Q1,
		q.Q2,
		q.Q3,
		maxv,
	}
	// replace NaN values with the previous or next value
	for i, v := range values {
		if math.IsNaN(v) {
			if i == 0 {
				values[i] = values[i+1]
			} else {
				values[i] = values[i-1]
			}
		}
	}
	return values, nil
}
